site_name: JumpIntoDSA

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav: 
  - 环境搭建: 
    - Environment/index.md
    - Environment/wsl_error.md
    - Environment/gdb.md
  - C语言专题讲解: 
    - C/index.md
    - C/recursion.md
    - C/pointer.md
    - C/cmdarg.md
  - C++快速入门: 
    - C++/index.md
    - 类和对象: C++/Class&Object.md
    - 构造析构: C++/Cons&Dest.md
    - 继承: C++/Inheritance.md
    - 多态: C++/Polymorphism.md
    - 运算符重载: C++/Overloading.md
    - 模板简介: C++/Templates.md
    - 内存分配: C++/Memory.md
    - 引用: C++/Reference.md
  - LAB0: LAB0/index.md
  - 数学基础: Math/index.md
  - 如何自学知识点: DIY/index.md
  - 练习题目: Practice/index.md
  - 补充讲解:
    - Supplement/index.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
